spring:
  server:
    port: 8080
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: markross89
    password: 16LUty1985!

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  application:
    name: farm-game-server
